name = "AdvectionFiniteDiff"
uuid = "a12f6a07-83fe-4746-a03f-256b9ea1d334"
authors = ["Will M. Farr <wfarr-vscholar@flatironinstitute.org>"]
version = "0.1.0"

[deps]
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
